task_management/urls.py
from django.contrib import admin
from django.urls import path,include
from debug_toolbar.toolbar import debug_toolbar_urls
from core.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('users/', include('users.urls')),
    path('', home, name='home'),
] + debug_toolbar_urls()

tasks/urls.py
from django.contrib import admin
from django.urls import path
from tasks.views import manager_dashboard,user_dashboard,test_view,create_task,view_task,update_task,delete_task
 
urlpatterns = [
    path('manager-dashboard/', manager_dashboard, name="manager-dashboard"),
    path('user-dashboard/', user_dashboard),
    path('test/', test_view),
    path('create-task/', create_task, name="create-task"),
    path('view-task/', view_task),
    path('update-task/<int:id>/', update_task, name="update-task"),
    path('delete-task/<int:id>/', delete_task, name="delete-task"),
]

tasks/models.py
from django.db import models

class employee(models.Model):
    name= models.CharField(max_length=100)
    email= models.EmailField(unique=True)
    def __str__(self):
        return self.name


class task(models.Model):
    status_choices = [
        ('PENDING', 'Pending'),
        ('IN PROGRESS', 'In Progress'),
        ('COMPLETED', 'Completed'),
    ]
    project= models.ForeignKey('project', on_delete=models.CASCADE, default=1)
    assigned_to= models.ManyToManyField(employee)
    title = models.CharField(max_length=200)
    description = models.TextField()
    is_completed = models.BooleanField(default=False)
    status = models.CharField(max_length=20, choices=status_choices, default='PENDING')
    due_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title

class taskdetails(models.Model):
    HIGH, MEDIUM, LOW = 'H', 'M', 'L'
    PRIORITY=(
        (HIGH, 'High'),
        (MEDIUM, 'Medium'),
        (LOW, 'Low')
    )
    task = models.OneToOneField(task, on_delete=models.CASCADE,related_name='details')
    #assigned_to = models.CharField(max_length=100)
    priority = models.CharField(max_length=1, choices=PRIORITY, default= 'L')
    notes = models.TextField(blank=True, null=True)
    def __str__(self):
        return f"Details of {self.task.title}"

class project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    start_date = models.DateField()
    def __str__(self):
        return self.name

tasks/forms.py
from django import forms
from tasks.models import employee, task, taskdetails, project

#django form for creating a new task
class TaskForm(forms.Form):
    title=forms.CharField(max_length=250)
    description=forms.CharField(widget=forms.Textarea)
    due_date=forms.DateField(widget=forms.SelectDateWidget)
    assigned_to=forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,)


    def __init__(self, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)
        employees = employee.objects.all()
        self.fields['assigned_to'].choices = [(emp.id, emp.name) for emp in employees]

#django Mixin form
# class styleMixin:
#     def add_style(self, *args):
#         for fieldname in args:
#             field = self.fields.get(fieldname)
#             if field:
#                 existing_classes = field.widget.attrs.get('class', '')
#                 field.widget.attrs['class'] = (existing_classes + ' ' if existing_classes else '') + 'border border-gray-300 rounded-md p-2 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent'


#django model from
class TaskModelForm(forms.ModelForm):
    class Meta:
        model = task
        fields = ['title', 'description', 'due_date', 'assigned_to']
        widgets = {
            'title': forms.TextInput(attrs={
                'size': 40,
                'placeholder': 'Enter task title'
                }),
            'description': forms.Textarea(attrs={
                'rows': 4,
                'cols': 40,
                'placeholder': 'Enter task description'
                }),
            'due_date': forms.SelectDateWidget(),
            'assigned_to': forms.CheckboxSelectMultiple(),
        }

class TaskDetailsModelForm(forms.ModelForm):
    class Meta:
        model = taskdetails
        fields = ['priority', 'notes']
        

tasks/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.db import models
from tasks.forms import TaskModelForm, TaskForm, TaskDetailsModelForm
from tasks.models import task as Task, taskdetails as TaskDetails, project as Project, employee as Employee
from django.contrib import messages



# Create your views here.
def manager_dashboard(request):
    type= request.GET.get('type','all')
    base_query= Task.objects.select_related('details').prefetch_related('assigned_to')

    #getting task count
    counts= Task.objects.aggregate(
        total_task= models.Count('id'),
        completed_task= models.Count('id', filter=models.Q(status='COMPLETED')),
        pending_task= models.Count('id', filter=models.Q(status='PENDING')),
        in_progress_task= models.Count('id', filter=models.Q(status='IN PROGRESS')),
    )

    #retrieving task based on type
    if type == 'completed':
        task= base_query.filter(status='COMPLETED')
    elif type == 'pending':
        task= base_query.filter(status='PENDING')
    elif type == 'in_progress':
        task= base_query.filter(status='IN PROGRESS')
    else:
        task= base_query.all()
    
    context= {
        'task': task,
        'counts': counts,
    }
    return render(request, "dashboard/manager-dashboard.html", context)

def user_dashboard(request):
    return render(request,"dashboard/user-dashboard.html")

def test_view(request):
    return render(request, "test.html")

def create_task(request):
    task_form= TaskModelForm()
    task_details_form= TaskDetailsModelForm()

    if request.method == 'POST':
        task_form= TaskModelForm(request.POST)
        task_details_form= TaskDetailsModelForm(request.POST)

        if task_form.is_valid() and task_details_form.is_valid():
            """using django ModelForm"""
            task=task_form.save()
            task_detail=task_details_form.save(commit=False)
            task_detail.task= task
            task_detail.save()

            messages.success(request, "Task created successfully!")
            return redirect('create-task')
    
    context = {'task_form': task_form, 'task_details_form': task_details_form}
    return render(request, "task_form.html", context)


def update_task(request ,id):
    task= Task.objects.get(id=id)
    task_form= TaskModelForm(instance=task)

    if task.details:
        task_details_form= TaskDetailsModelForm(instance=task.details)
        
    if request.method == 'POST':
        task_form= TaskModelForm(request.POST, instance=task)
        task_details_form= TaskDetailsModelForm(request.POST, instance=task.details)

        if task_form.is_valid() and task_details_form.is_valid():
            """using django ModelForm"""
            task=task_form.save()
            task_detail=task_details_form.save(commit=False)
            task_detail.task= task
            task_detail.save()

            messages.success(request, "Task  successfully!")
            return redirect('update-task',id=id)
    
    context = {'task_form': task_form, 
               'task_details_form': task_details_form}
    return render(request, "task_form.html", context)

def delete_task(request, id):
    if request.method == 'POST':
        task= Task.objects.get(id=id)
        task.delete()
        messages.success(request, "Task Deleted successfully!")
        return redirect('manager-dashboard')
    else:
        messages.error(request, "Invalid request method.")
        return redirect('manager-dashboard')
    
    



def view_task(request):
    # select related query(foreign key, one to one fields)
    task= Task.objects.select_related('details').all()
    return render(request, "show_task.html", {'task': task,})

tasks/templates/dashboard/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'css/output.css' %}">
</head>
<body class="p-6 bg-gray-100">
   <div class="max-w-[1400px] mx-auto">
     <!-- header -->
     <header class="flex justify-between item-center mb-8 ">
        <h1 class="text-2xl font-semibold">Dashboard</h1>
        <div class="flex item-center justify-center gap-4">
            <button class="p-2 rounded-full hover:bg-gray-200 relative">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 0 0 5.454-1.31A8.967 8.967 0 0 1 18 9.75V9A6 6 0 0 0 6 9v.75a8.967 8.967 0 0 1-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 0 1-5.714 0m5.714 0a3 3 0 1 1-5.714 0" />
                </svg>
              </button>
            <button class="w-10 h-10 bg-blue-500 rounded-full text-white font-semibold">
                B
            </button>
        </div>
     </header>
     <main>
        <!-- status_grid -->
        <div class="grid grid-cols-4 gap-5">
            <a href="{% url 'manager-dashboard'%}?type=all">
            <div class="bg-white rounded-xl p-6 shadow-sm">
                <h3 class="text-sm font-medium text-gray-500 mb-4">Total Task</h3>
                <div class="flex justify-between items-start">
                    <div class="">
                        <p class="text-3xl font-semibold mb-1">{{counts.total_task}}</p>
                        <p class="text-gray-500 text-sm ">111 last month</p>
                    </div>
                    <div class="rounded-full bg-blue-100 p-3">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 text-blue-600">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M15.666 3.888A2.25 2.25 0 0 0 13.5 2.25h-3c-1.03 0-1.9.693-2.166 1.638m7.332 0c.055.194.084.4.084.612v0a.75.75 0 0 1-.75.75H9a.75.75 0 0 1-.75-.75v0c0-.212.03-.418.084-.612m7.332 0c.646.049 1.288.11 1.927.184 1.1.128 1.907 1.077 1.907 2.185V19.5a2.25 2.25 0 0 1-2.25 2.25H6.75A2.25 2.25 0 0 1 4.5 19.5V6.257c0-1.108.806-2.057 1.907-2.185a48.208 48.208 0 0 1 1.927-.184" />
                          </svg>                          
                    </div>                     
                </div>
            </div>
            </a>

            <a href="{% url 'manager-dashboard'%}?type=completed">
            <div class="bg-white rounded-xl p-6 shadow-sm">
                <h3 class="text-sm font-medium text-gray-500 mb-4">Completed Task</h3>
                <div class="flex justify-between items-start">
                    <div class="">
                        <p class="text-3xl font-semibold mb-1">{{counts.completed_task}}</p>
                        <p class="text-gray-500 text-sm ">111 last month</p>
                    </div>
                    <div class="rounded-full bg-green-100 p-3">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 text-green-600">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75 11.25 15 15 9.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                          </svg>
                                                   
                    </div>                     
                </div>
            </div>
            </a>

            <a href="{% url 'manager-dashboard'%}?type=in_progress">
            <div class="bg-white rounded-xl p-6 shadow-sm">
                <h3 class="text-sm font-medium text-gray-500 mb-4">Task In progress</h3>
                <div class="flex justify-between items-start">
                    <div class="">
                        <p class="text-3xl font-semibold mb-1">{{counts.in_progress_task}}</p>
                        <p class="text-gray-500 text-sm ">111 last month</p>
                    </div>
                    <div class="rounded-full bg-yellow-100 p-3">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 text-yellow-600">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                          </svg>
                                                   
                    </div>                     
                </div>
            </div>
            </a>

            <a href="{% url 'manager-dashboard'%}?type=pending">
            <div class="bg-white rounded-xl p-6 shadow-sm">
                <h3 class="text-sm font-medium text-gray-500 mb-4">TODOS</h3>
                <div class="flex justify-between items-start">
                    <div class="">
                        <p class="text-3xl font-semibold mb-1">{{counts.pending_task}}</p>
                        <p class="text-gray-500 text-sm ">111 last month</p>
                    </div>
                    <div class="rounded-full bg-purple-100 p-3">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 text-purple-600">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M15.666 3.888A2.25 2.25 0 0 0 13.5 2.25h-3c-1.03 0-1.9.693-2.166 1.638m7.332 0c.055.194.084.4.084.612v0a.75.75 0 0 1-.75.75H9a.75.75 0 0 1-.75-.75v0c0-.212.03-.418.084-.612m7.332 0c.646.049 1.288.11 1.927.184 1.1.128 1.907 1.077 1.907 2.185V19.5a2.25 2.25 0 0 1-2.25 2.25H6.75A2.25 2.25 0 0 1 4.5 19.5V6.257c0-1.108.806-2.057 1.907-2.185a48.208 48.208 0 0 1 1.927-.184" />
                          </svg>                          
                    </div>                     
                </div>
            </div>
            </a>
            
        </div>  

        {% block tasks %}{% endblock tasks %}
     </main>
   </div>
</body>
</html>

  

tasks/templates/dashboard/manager-dashboard.html
{% extends "dashboard/dashboard.html" %}
{% block title %}Manager Dashboard{% endblock title %}
{% block tasks %}

<div class="container mx-auto p-4">
    {% if messages %}
        {% for message in messages %}
        <div class="px-2 py-1 
            {% if message.tags == "success" %} bg-green-400 
            {% elif message.tags == "error" %} bg-red-400 
            {% elif message.tags == "warning" %} bg-yellow-400 
            {% else %} bg-blue-400 
            {% endif %}
        ">
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}
</div>
<!-- task_table -->
         <div class="bg-white rounded-xl shadow-sm mt-8 ">
            <div class="grid grid-cols-4 p-4 border-b border-gray-100 text-sm text-gray-500">
                <div>Task Title</div>
                <div>Priority</div>
                <div>Team</div>
                <div>Created At</div>
            </div>


            <!-- task_item -->
            <div class="divide-y divide-gray-100  ">
                {% for task in task %}
                    <div class="grid grid-cols-4 p-4 gap-4 item-center" >
                    <div class="flex items-center gap-2">
                        <div class="w-2 h-2 bg-green-600 rounded-full"></div>
                        <div>
                            <span>{{task.title}}</span>
                            <div>
                                <a href="{% url "update-task" task.id %}" class= "px-2 py-1 bg bg-green-600 text-black">Edit</a>
                                <form action="{% url "delete-task" task.id %}" method="POST">
                                    <button type="submit" class= "px-2 py-1 bg bg-red-600 text-black">Delete</button>
                                    {% csrf_token %}
                                </form>
                        </div>
                            </div>
                    </div>
                    <div>
                        <span class="px-3 py-1 rounded-full bg-blue-50 text-blue-600 text-sm">{{task.details.get_priority_display}}</span>
                    </div>
                    <div>
                        <div class="flex -space-x-2">
                            {% for emp in task.assigned_to.all %}
                                <div class="w-8 h-8 rounded-full bg-blue-500 flex items-center justify-center text-white text-sm border-2 border-white">{{emp.name|slice:':2'}}</div>
                            {% endfor %}
                        </div>
                    </div>
                    <div>
                        <span class="text-gray-500">{{task.created_at| timesince}}</span>
                    </div>
                </div>
                {% endfor %}
            </div>
         </div> 

{% endblock tasks %}

tasks/templates/dashboard/user-dashboard.html
{% extends "dashboard/dashboard.html" %}
{% block title %}User Dashboard{% endblock title %}
{% block tasks %}
<!-- 2nd_part -->
             <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-2 mt-6">
                <!-- left -->
                <div class="bg-white rounded-md shadow-sm  p-4">
                    <h1 class="font-bold">Today's Tasks</h1>
                    <div class="flex justify-between items-center ">
                        <div class="">
                            <div class="flex items-center gap-2">
                                <div class="w-2 h-2 bg-green-600 rounded-full"></div>
                                <div>
                                    <span class="text-sm">Complete Project Proposal</span>
                                </div>
                            </div>
                            <div class="flex items-center gap-2">
                                <div class="w-2 h-2 bg-yellow-600 rounded-full"></div>
                                <div>
                                    <span class="text-sm">Review Team Update</span>
                                </div>
                            </div>
                            <div class="flex items-center gap-2">
                                <div class="w-2 h-2 bg-blue-600 rounded-full"></div>
                                <div>
                                    <span class="text-sm">Prepare for client meeting</span>
                                </div>
                            </div>
                        </div>
                        <div class="text-gray-500 text-sm">
                            <p>High</p>
                            <p>Normal</p>
                            <p>Low</p>
                        </div>
                    </div>
                </div>
                <!-- right -->
                 <div>
                    <div class="bg-white rounded-md shadow-sm">
                        <div>
                            <h1 class="font-bold p-4">Today's Tasks</h1>
                        </div>
                        <div class="grid grid-cols-4 p-4 border-b border-gray-100 text-sm text-gray-500">
                            <div>Task Title</div>
                            <div>Priority</div>
                            <div>Team</div>
                            <div>Created At</div>
                        </div>
                        <!-- task_item -->
                        <div class="">
                            <div class="grid grid-cols-4 p-4 gap-4 item-center" >
                                <div class="flex items-center gap-2">
                                    <div class="w-2 h-2 bg-green-600 rounded-full"></div>
                                    <div>
                                        <span class="text-sm">Test Low Task</span>
                                    </div>
                                </div>
                                <div>
                                    <span class="px-3 py-1 rounded-full bg-blue-50 text-blue-600 text-sm">Low</span>
                                </div>
                                <div>
                                    <div class="flex -space-x-2">
                                        <div class="w-8 h-8 rounded-full bg-blue-500 flex items-center justify-center text-white text-sm border-2 border-white">JS</div>
                                        <div class="w-8 h-8 rounded-full bg-green-500 flex items-center justify-center text-white text-sm border-2 border-white">CA</div>
                                        <div class="w-8 h-8 rounded-full bg-yellow-500 flex items-center justify-center text-white text-sm border-2 border-white">B</div>
                                    </div>
                                </div>
                                <div>
                                    <span class="text-gray-500">9 months ago</span>
                                </div>
                            </div>
                        </div>
                        <div class="divide-y divide-gray-100  ">
                            <div class="grid grid-cols-4 p-4 gap-4 item-center" >
                                <div class="flex items-center gap-2">
                                    <div class="w-2 h-2 bg-yellow-600 rounded-full"></div>
                                    <div>
                                        <span class="text-sm">Test Task</span>
                                    </div>
                                </div>
                                <div>
                                    <span class="px-3 py-1 rounded-full bg-yellow-100 text-yellow-600 text-sm">Normal</span>
                                </div>
                                <div>
                                    <div class="flex -space-x-2">
                                        <div class="w-8 h-8 rounded-full bg-red-500 flex items-center justify-center text-white text-sm border-2 border-white">AJ</div>
                                        <div class="w-8 h-8 rounded-full bg-purple-500 flex items-center justify-center text-white text-sm border-2 border-white">EV</div>
                                        <div class="w-8 h-8 rounded-full bg-yellow-500 flex items-center justify-center text-white text-sm border-2 border-white">B</div>
                                    </div>
                                </div>
                                <div>
                                    <span class="text-gray-500">9 months ago</span>
                                </div>
                            </div>
                        </div>
                        <div class="divide-y divide-gray-100  ">
                            <div class="grid grid-cols-4 p-4 gap-4 item-center" >
                                <div class="flex items-center gap-2">
                                    <div class="w-2 h-2 bg-orange-600 rounded-full"></div>
                                    <div>
                                        <span class="text-sm">Test Task</span>
                                    </div>
                                </div>
                                <div>
                                    <span class="px-3 py-1 rounded-full bg-orange-100 text-red-500 text-sm">High</span>
                                </div>
                                <div>
                                    <div class="flex -space-x-2">
                                        <div class="w-8 h-8 rounded-full bg-blue-500 flex items-center justify-center text-white text-sm border-2 border-white">EV</div>
                                        <div class="w-8 h-8 rounded-full bg-green-500 flex items-center justify-center text-white text-sm border-2 border-white">JS</div>
                                        <div class="w-8 h-8 rounded-full bg-red-500 flex items-center justify-center text-white text-sm border-2 border-white">CA</div>
                                        <div class="w-8 h-8 rounded-full bg-yellow-500 flex items-center justify-center text-white text-sm border-2 border-white">B</div>
                                    </div>
                                </div>
                                <div>
                                    <span class="text-gray-500">9 months ago</span>
                                </div>
                            </div>
                        </div>
                     </div>
                 </div>
             </div>
{% endblock tasks %}